project_name: pinba-influxer

# Build customization
builds:
  - binary: pinba-influxer
    goos:
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  files:
    - LICENSE
    - README.md
    - config.yml.example

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  homepage: https://github.com/olegfedoseev/pinba-influxdb
  maintainer: Oleg Fedoseev <oleg.fedoseev@me.com>
  description: Pinba gateway to InfluxDB
  license: MIT
  formats:
    - deb
  files:
    "scripts/etc/pinba-influxer/": "/etc/pinba-influxer"
    "scripts/usr/lib/pinba-influxer/": "/usr/lib/pinba-influxer"
    "scripts/usr/lib/pinba-influxer/pinba-influxer.service": "/usr/lib/pinba-influxer/pinba-influxer.service"
    "scripts/usr/lib/pinba-influxer/pinba-influxer.service": "/lib/systemd/system/pinba-influxer.service"
  config_files:
    "scripts/etc/pinba-influxer/config.yml.example": "/etc/pinba-influxer/config.yml"

release:
  github:
    owner: olegfedoseev
    name: pinba-influxdb

  # If set to true, will not auto-publish the release.
  draft: false
  # If set to true, will mark the release as not ready for production.
  prerelease: true

